### ISSUE TITLE
Glight application icon

### ISSUE THREAD

**Issue by jld3103** [aroffringa/glight#255]
Hi, I just tried out Glight the first time and create a package for Arch Linux: https://github.com/jld3103/PKGBUILDs/tree/main/glight-git
It would be nice to have an icon for the .desktop file to show.
Also maybe including a default .desktop file in the repo that gets installed by make is a good idea, so it's directly accessible for end users.

**Comment by aroffringa** [comment]
Thanks, that's a good idea! I'll make one.
